# Generated by Django 2.2 on 2019-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20191210_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='house_unit_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
